#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-ps
Version  : 1.3.0
Release  : 13
URL      : https://cran.r-project.org/src/contrib/ps_1.3.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/ps_1.3.0.tar.gz
Summary  : List, Query, Manipulate System Processes
Group    : Development/Tools
License  : BSD-3-Clause
Requires: R-ps-lib = %{version}-%{release}
BuildRequires : R-assertthat
BuildRequires : R-cli
BuildRequires : R-rlang
BuildRequires : R-withr
BuildRequires : buildreq-R

%description
# ps
> List, Query, Manipulate System
Processes
[![lifecycle](https://img.shields.io/badge/lifecycle-maturing-blue.svg)](https://www.tidyverse.org/lifecycle/#maturing)
[![Travis build
status](https://travis-ci.org/r-lib/ps.svg?branch=master)](https://travis-ci.org/r-lib/ps)
[![AppVeyor build
status](https://ci.appveyor.com/api/projects/status/github/r-lib/ps?branch=master&svg=true)](https://ci.appveyor.com/project/gaborcsardi/ps)
[![CRAN
status](https://www.r-pkg.org/badges/version/ps)](https://cran.r-project.org/package=ps)
[![CRAN RStudio mirror
downloads](https://cranlogs.r-pkg.org/badges/ps)](https://www.r-pkg.org/pkg/ps)
[![Coverage
status](https://codecov.io/gh/r-lib/ps/branch/master/graph/badge.svg)](https://codecov.io/github/r-lib/ps?branch=master)

%package lib
Summary: lib components for the R-ps package.
Group: Libraries

%description lib
lib components for the R-ps package.


%prep
%setup -q -c -n ps

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1552873349

%install
export SOURCE_DATE_EPOCH=1552873349
rm -rf %{buildroot}
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library ps
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library ps
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library ps
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc  ps || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/ps/DESCRIPTION
/usr/lib64/R/library/ps/INDEX
/usr/lib64/R/library/ps/LICENSE
/usr/lib64/R/library/ps/Meta/Rd.rds
/usr/lib64/R/library/ps/Meta/features.rds
/usr/lib64/R/library/ps/Meta/hsearch.rds
/usr/lib64/R/library/ps/Meta/links.rds
/usr/lib64/R/library/ps/Meta/nsInfo.rds
/usr/lib64/R/library/ps/Meta/package.rds
/usr/lib64/R/library/ps/NAMESPACE
/usr/lib64/R/library/ps/NEWS.md
/usr/lib64/R/library/ps/R/ps
/usr/lib64/R/library/ps/R/ps.rdb
/usr/lib64/R/library/ps/R/ps.rdx
/usr/lib64/R/library/ps/WORDLIST
/usr/lib64/R/library/ps/bin/px
/usr/lib64/R/library/ps/help/AnIndex
/usr/lib64/R/library/ps/help/aliases.rds
/usr/lib64/R/library/ps/help/paths.rds
/usr/lib64/R/library/ps/help/ps.rdb
/usr/lib64/R/library/ps/help/ps.rdx
/usr/lib64/R/library/ps/html/00Index.html
/usr/lib64/R/library/ps/html/R.css
/usr/lib64/R/library/ps/internals.md
/usr/lib64/R/library/ps/tests/testthat.R
/usr/lib64/R/library/ps/tests/testthat/helpers.R
/usr/lib64/R/library/ps/tests/testthat/test-cleanup-reporter.R
/usr/lib64/R/library/ps/tests/testthat/test-common.R
/usr/lib64/R/library/ps/tests/testthat/test-connections.R
/usr/lib64/R/library/ps/tests/testthat/test-finished.R
/usr/lib64/R/library/ps/tests/testthat/test-kill-tree.R
/usr/lib64/R/library/ps/tests/testthat/test-linux.R
/usr/lib64/R/library/ps/tests/testthat/test-macos.R
/usr/lib64/R/library/ps/tests/testthat/test-pid-reuse.R
/usr/lib64/R/library/ps/tests/testthat/test-posix-zombie.R
/usr/lib64/R/library/ps/tests/testthat/test-posix.R
/usr/lib64/R/library/ps/tests/testthat/test-system.R
/usr/lib64/R/library/ps/tests/testthat/test-utils.R
/usr/lib64/R/library/ps/tests/testthat/test-windows.R

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/ps/libs/ps.so
/usr/lib64/R/library/ps/libs/ps.so.avx2
/usr/lib64/R/library/ps/libs/ps.so.avx512
